Feature transport request search
DevEpos/abap-code-search-tools pull request #19
Opened 2023-12-09 18:53 UTC by reichr-dev

2023-12-12 22:17 UTC, stockbal requested changes

2023-12-12 22:17 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +         WHERE objecttype IN @search_ranges-object_type_range
If e.g. type `CLAS` has been passed as filter, all `LIMU` types will be automatically excluded from the search.  
To prevent this, the values in `search_ranges-object_type_ranges` should be expanded -> `CLAS` becomes `CLAS`, `CLSD`, `CPRI`, ...

This should be done before the `WITH` clause

2023-12-12 22:17 UTC, stockbal commented on src/zif_adcoset_ty_global.intf.abap
> +  TYPES ty_tadir_objects_deep TYPE STANDARD TABLE OF ty_tadir_object_deep WITH EMPTY KEY.
Rename to `ty_tadir_object` and `ty_tadir_objects`.
The current types with those names should be renamed to `ty_tadir_object_info` and `ty_tadir_object_infos`.

2023-12-12 22:17 UTC, stockbal commented on src/zcl_adcoset_csp_fugr.clas.abap
> +    IF line_exists( includes[ is_function_include = abap_true ] ) AND function_names_loaded = abap_false.
Comparison `function_names_loaded = abap_false` makes no sense as it is always `abap_false` at this point.
This should be replaced with `object-subobjects IS NOT INITIAL`.

2023-12-12 22:17 UTC, stockbal commented on src/zcl_adcoset_csp_fugr.clas.abap
> -          ENDIF.
This code is still required for the cases when `object-subobjects` is empty and a match in a function module occurred.

2023-12-13 18:20 UTC, reichr-dev commented on src/zif_adcoset_ty_global.intf.abap
> +  TYPES ty_tadir_objects_deep TYPE STANDARD TABLE OF ty_tadir_object_deep WITH EMPTY KEY.
Should I name it ty_tadir_object_infos  or  ty_tadir_objects_info

2023-12-13 18:24 UTC, reichr-dev commented on src/zcl_adcoset_csp_fugr.clas.abap
> +    IF line_exists( includes[ is_function_include = abap_true ] ) AND function_names_loaded = abap_false.
The new condition would be 
IF line_exists( includes[ is_function_include = abap_true ] ) OR object-subobjects IS NOT INITIAL.  ,right?

And I can remove the function_names_loaded variable completely, right?

2023-12-13 18:51 UTC, stockbal commented on src/zif_adcoset_ty_global.intf.abap
> +  TYPES ty_tadir_objects_deep TYPE STANDARD TABLE OF ty_tadir_object_deep WITH EMPTY KEY.
`ty_tadir_object_infos` for the table type and `ty_tadir_object_info` for the line type

2023-12-16 12:37 UTC, stockbal requested changes
Please perform the following changes, to move the logic that is only required for the transport request search to the specific scope class.

### Changes in class `ZCL_ADCOSET_SEARCH_SCOPE_TR`

![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/dad82d60-2d47-465d-b97f-d8ff0911290f)
- Create new type `ty_scope_package` in interface `zif_adcoset_ty_global` with the following components:
   - count TYPE i
   - objects TYPE zif_adcoset_ty_global=>ty_tadir_objects

![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/b8d86706-f726-426b-a2d5-522d80a354cc)

1) delete and fill the `count` component of the scope package instead
2) Create local type `ty_tadir_object_extended` and add this component there. Create a local table type with this line type. In the method `next_package` a `CORRESPONDING #( DEEP )` will be performed at the end
3) No longer required and can be deleted

![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/90797cd8-6ba5-495c-9b5c-a0ef6fd20049)

Method `skip_search` is no longer required. The filtering can be moved to `next_package`

### Changes in class `ZCL_ADCOSET_SEARCH_QUERY`

![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/b60b9338-9d14-41c0-8a61-b4400d997cb6)

- Store result of the `next_package` call in a new variable `package` and then iterate over the component `objects` 
- Remove the if-block with the call to `skip_search`
- Move method call (see screenshot) after the loop and pass parameter `package-count` instead

### Changes in class `ZCL_ADCOSET_PARL_SEARCH_QUERY`

![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/e5c0d490-52d4-4d40-b427-23eafd514e61)

Rename component `objects` of `ty_search_package` in `scope_package` and change type of that component to `ty_scope_package`

### Changes in class `ZCL_ADCOSET_SEARCH_SCOPE_FINAL`

- Rename parameter `objects` of method `constructor` to `package` and change type to `ty_scope_package`.
- Rename attribute `objects` to `package` and use the same type as in the constructor parameter

### Changes in class `ZCL_ADCOSET_SEARCH_SCOPE_FAC`

- Rename `objects` parameter of method `create_final_scope` to `package` with type `ty_scope_package`

2023-12-16 12:48 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.locals_imp.abap
> +                    has_deleted_subobjects = xsdbool( function_exists = abap_false ) ).
I am not sure if this logic is correct. Paired with the call in method `skip_search` I believe all function modules of a specific function group will be skipped if e.g. the last one no longer exists.

2023-12-22 16:45 UTC, stockbal requested changes

2023-12-22 16:45 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +  ENDMETHOD.
I think we can move the whole logic also in the local class. The method `determine_tadir_obj_for_limu` is then to be moved as well into the local class. Additionally the `CONSTRUCTOR` of the local class needs a new parameter to pass the limu objects.
The new method to process all limu objects I would name `RUN`.

2023-12-22 16:45 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +                                    ( object ) ) ) ).
Replace with constructor call to limu processor and a subsequent call to the new method `run` (see comment in method `process_limu_objects`).

e.g. `objects = new lcl_limu_processor( ... )->run( )`

2023-12-22 16:51 UTC, stockbal requested changes

2023-12-22 16:51 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +                                ( object ) ) ).
Either pass the complete `tr_objects` table to the method and move the `R3TR` filter to the loop in the method, or replace the method call and adjust the append in the `FOR` loop to the `VALUE` call in the method.

2023-12-27 19:44 UTC, stockbal requested changes

2023-12-27 19:44 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +    IF current_offset < max_rows.
The usage of `current_offset` is wrong here and can lead to an infinite loop. It has to be changed to `IF result-count < max_rows`.

2023-12-27 20:21 UTC, stockbal requested changes

2023-12-27 20:21 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +                    objectname AS obj_name
Select `DevelopmentPackage` as well

2023-12-27 20:21 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +      result = VALUE #( BASE result
include `package_name` in result

2023-12-27 20:21 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.locals_imp.abap
> +      objects = VALUE #( BASE objects
include `package_name` in result

2023-12-27 20:42 UTC, stockbal requested changes

2023-12-27 20:42 UTC, stockbal commented on src/zif_adcoset_ty_global.intf.abap
> +         ty_tr_request_objects TYPE SORTED TABLE OF ty_tr_request_object WITH UNIQUE KEY obj_name pgmid obj_type.
Reorder key to 
- pgmid 
- obj_type 
- obj_name

2023-12-27 21:54 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +
Call new methods
- fill_missing_tadir_infos
- post_filter

2023-12-27 21:57 UTC, stockbal requested changes
Apply the following changes, so grouping by package and filtering by *owner*, *package* and *created date* can be performed (Part 2)

2023-12-27 21:57 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +
Call new methods
- fill_missing_tadir_infos
- post_filter

2023-12-27 21:57 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.abap
Create new methods in class `ZCL_ADCOSET_SEARCH_SCOPE_TR`
- fill_missing_tadir_info  
   This method should fill the empty fields `package_name`, `owner` and `created_date`. Use empty `package_name` as matching criteria
- post_filter  
   apply filters *package*, *owner* and *created date* and delete the objects that don't match these filters

2023-12-28 06:43 UTC, reichr-dev commented on src/zadcoset_transportsourcecodobj.ddls.asddls
> +      obj_name as ObjectName
CreatedAt or CreatedDate?

2023-12-28 06:53 UTC, reichr-dev commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +      result = VALUE #( BASE result
as result does not contain the created_date we could already apply the created_on filter before moving the data to result

2023-12-28 09:02 UTC, reichr-dev commented on src/zif_adcoset_ty_global.intf.abap
> +         ty_tr_request_objects TYPE SORTED TABLE OF ty_tr_request_object WITH UNIQUE KEY obj_name pgmid obj_type.
This is the sorting that I use for the selection too. 

The idea behind this sorting (obj_name pgmid obj_type) was: if I have multiple packages (in case of a high number of objects in a TR) the chance that multiple limu objects ( e.g. meth) of the same main object fall in the same package is higher and I avoid multiple searches on the same main object

2023-12-28 09:04 UTC, reichr-dev commented on src/zcl_adcoset_search_scope_tr.clas.abap
> +
suggestion would be a slightly different approach to apply these methods only in the limu processor ( see commit )

2023-12-28 09:04 UTC, reichr-dev commented on src/zcl_adcoset_search_scope_tr.clas.abap
suggestion would be a slightly different approach to apply these methods only in the limu processor ( see commit )

2023-12-28 10:48 UTC, reichr-dev commented
issues we might still have to consider:
1. the filters owner and created on apply to the main object which might not be the object that was included in the TR
2. through the post filtering the Code Search Runtime Information might contain not fully understandable information

2023-12-28 16:12 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.locals_imp.abap
> +        AND createddate IN @search_ranges-created_on_range
- Add additional conditions for `developmentpackage` and `owner`
- Use a sorted table type to store the select result with key `objectname`, `objecttype`

2023-12-28 16:12 UTC, stockbal commented on src/zcl_adcoset_search_scope_tr.clas.locals_imp.abap
> +
Uncomment these lines

2023-12-28 16:16 UTC, stockbal commented
> issues we might still have to consider:
> 
> 1. the filters owner and created on apply to the main object which might not be the object that was included in the TR
> 2. through the post filtering the Code Search Runtime Information might contain not fully understandable information

1. That's ok, it is the same as for a *normal* code search (i.e. without transport request filter)
2.  I will rename the part of the runtime information to *Processed Objects*. That should make it clearer that these objects were not necessarily searched.
![image](https://github.com/DevEpos/abap-code-search-tools/assets/35834861/2c9987b6-9662-43c8-8fe9-99570832a56d)

2024-02-12 09:01 UTC, stockbal approved these changes

2024-02-12 09:01 UTC, merged